name:                slow-numbers
version:             0.1.0.0
github:              "oisdk/slow-numbers"
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2016 Donnacha Oisín Kidney"
license:             MIT
category:            Numeric
extra-source-files:  README.md

description:         Library for the slower number types, like Peano, Church, etc.

dependencies:
- base >= 4.10
- singletons >= 2
- deepseq >= 1.4

library:
  source-dirs: src
  other-modules: Numeric.Church.Prelude

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
- -fwarn-redundant-constraints
- -Wcompat

tests:
  slow-numbers-test:
    main:                Spec.hs
    source-dirs:      test
    dependencies:
    - slow-numbers
    - hedgehog
    - hedgehog-checkers
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  slow-numbers-doctests:
    main: doctests.hs
    source-dirs: doctest
    ghc-options:
    - -threaded
    dependencies:
    - slow-numbers
    - QuickCheck
    - doctest

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - slow-numbers
    - criterion
    - random
